//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliverBotCustomization.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Output : global::System.Configuration.ApplicationSettingsBase {
        
        private static Output defaultInstance = ((Output)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Output())));
        
        public static Output Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool WriteOutputFile2CommonFolder {
            get {
                return ((bool)(this["WriteOutputFile2CommonFolder"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputEmptyFieldSubstitute {
            get {
                return ((string)(this["OutputEmptyFieldSubstitute"]));
            }
            set {
                this["OutputEmptyFieldSubstitute"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\t")]
        public string OutputFieldSeparator {
            get {
                return ((string)(this["OutputFieldSeparator"]));
            }
            set {
                this["OutputFieldSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000000")]
        public int OutputFileChunkSizeInBytes {
            get {
                return ((int)(this["OutputFileChunkSizeInBytes"]));
            }
            set {
                this["OutputFileChunkSizeInBytes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("output.tab")]
        public string OutputFileName {
            get {
                return ((string)(this["OutputFileName"]));
            }
            set {
                this["OutputFileName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string OutputFieldSeparatorSubstitute {
            get {
                return ((string)(this["OutputFieldSeparatorSubstitute"]));
            }
            set {
                this["OutputFieldSeparatorSubstitute"] = value;
            }
        }
    }
}
