//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliverBotCustomization.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Spider : global::System.Configuration.ApplicationSettingsBase {
        
        private static Spider defaultInstance = ((Spider)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Spider())));
        
        public static Spider Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public byte DownloadedContentTypePattern {
            get {
                return ((byte)(this["DownloadedContentTypePattern"]));
            }
            set {
                this["DownloadedContentTypePattern"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ComplyRobotProtocol {
            get {
                return ((bool)(this["ComplyRobotProtocol"]));
            }
            set {
                this["ComplyRobotProtocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MaxOpenLinkDepth {
            get {
                return ((int)(this["MaxOpenLinkDepth"]));
            }
            set {
                this["MaxOpenLinkDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int MaxPageCountPerSite {
            get {
                return ((int)(this["MaxPageCountPerSite"]));
            }
            set {
                this["MaxPageCountPerSite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("pdf|msi|exe|gif|jpg|jpeg|bmp|rtf|ps|arj|zip|z|gzip|rar|gz|tar|tgz|bz|bz2|wav|mp3|" +
            "au|aiff|bin|mpg|mpeg|mov|qt|tif|tiff|avi|ram|ra|arc|hqx|sit|sea|uu|png|css|ico|c" +
            "l|jar")]
        public string NonSpideredExtensions {
            get {
                return ((string)(this["NonSpideredExtensions"]));
            }
            set {
                this["NonSpideredExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int UnchangableDomainPartNumber {
            get {
                return ((int)(this["UnchangableDomainPartNumber"]));
            }
            set {
                this["UnchangableDomainPartNumber"] = value;
            }
        }
    }
}
