//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CliverBotCustomization.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    public sealed partial class Web : global::System.Configuration.ApplicationSettingsBase {
        
        private static Web defaultInstance = ((Web)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Web())));
        
        public static Web Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public string DownloadableContentTypePattern {
            get {
                return ((string)(this["DownloadableContentTypePattern"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("text/xml,text/html;q=0.9,text/plain;q=0.8")]
        public string HttpRequestAcceptHeader {
            get {
                return ((string)(this["HttpRequestAcceptHeader"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int CrawlTimeIntervalInMss {
            get {
                return ((int)(this["CrawlTimeIntervalInMss"]));
            }
            set {
                this["CrawlTimeIntervalInMss"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CloseWebBrowserDialogsAutomatically {
            get {
                return ((bool)(this["CloseWebBrowserDialogsAutomatically"]));
            }
            set {
                this["CloseWebBrowserDialogsAutomatically"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int HttpRequestTimeoutInSeconds {
            get {
                return ((int)(this["HttpRequestTimeoutInSeconds"]));
            }
            set {
                this["HttpRequestTimeoutInSeconds"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("CliverBot")]
        public string HttpUserAgent {
            get {
                return ((string)(this["HttpUserAgent"]));
            }
            set {
                this["HttpUserAgent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000000")]
        public int MaxDownloadedFileLength {
            get {
                return ((int)(this["MaxDownloadedFileLength"]));
            }
            set {
                this["MaxDownloadedFileLength"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1")]
        public int MaxHttpRedirectionCount {
            get {
                return ((int)(this["MaxHttpRedirectionCount"]));
            }
            set {
                this["MaxHttpRedirectionCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("60")]
        public int WebBrowserPageCompletedTimeoutInSeconds {
            get {
                return ((int)(this["WebBrowserPageCompletedTimeoutInSeconds"]));
            }
            set {
                this["WebBrowserPageCompletedTimeoutInSeconds"] = value;
            }
        }
    }
}
