//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliver.Bot.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Input : global::System.Configuration.ApplicationSettingsBase {
        
        private static Input defaultInstance = ((Input)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Input())));
        
        public static Input Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("input.txt")]
        public string InputFile {
            get {
                return ((string)(this["InputFile"]));
            }
            set {
                this["InputFile"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(",")]
        public string InputFieldSeparator {
            get {
                return ((string)(this["InputFieldSeparator"]));
            }
            set {
                this["InputFieldSeparator"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\',\'")]
        public string EscapedInputFieldSeparator {
            get {
                return ((string)(this["EscapedInputFieldSeparator"]));
            }
            set {
                this["EscapedInputFieldSeparator"] = value;
            }
        }
    }
}
