#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliver.CrawlerHost.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="CliverCrawlerHost")]
	public partial class CrawlerHostDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCrawler(Crawler instance);
    partial void UpdateCrawler(Crawler instance);
    partial void DeleteCrawler(Crawler instance);
    partial void InsertMessage(Message instance);
    partial void UpdateMessage(Message instance);
    partial void DeleteMessage(Message instance);
    partial void InsertService(Service instance);
    partial void UpdateService(Service instance);
    partial void DeleteService(Service instance);
    partial void InsertSetting(Setting instance);
    partial void UpdateSetting(Setting instance);
    partial void DeleteSetting(Setting instance);
    #endregion
		
		public CrawlerHostDataContext() : 
				base(global::Cliver.CrawlerHost.Properties.Settings.Default.CliverCrawlerHostConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public CrawlerHostDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CrawlerHostDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CrawlerHostDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public CrawlerHostDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Crawler> Crawlers
		{
			get
			{
				return this.GetTable<Crawler>();
			}
		}
		
		public System.Data.Linq.Table<Message> Messages
		{
			get
			{
				return this.GetTable<Message>();
			}
		}
		
		public System.Data.Linq.Table<Service> Services
		{
			get
			{
				return this.GetTable<Service>();
			}
		}
		
		public System.Data.Linq.Table<Setting> Settings
		{
			get
			{
				return this.GetTable<Setting>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Crawlers")]
	public partial class Crawler : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private int _State;
		
		private string _Site;
		
		private int _Command;
		
		private int _RunTimeSpan;
		
		private int _CrawlProductTimeout;
		
		private int _YieldProductTimeout;
		
		private string _AdminEmails;
		
		private string _Comment;
		
		private int _RestartDelayIfBroken;
		
		private System.Nullable<System.DateTime> @__SessionStartTime;
		
		private System.Nullable<int> @__LastSessionState;
		
		private System.DateTime @__NextStartTime;
		
		private System.Nullable<System.DateTime> @__LastStartTime;
		
		private System.Nullable<System.DateTime> @__LastEndTime;
		
		private System.Nullable<int> @__LastProcessId;
		
		private string @__LastLog;
		
		private string @__Archive;
		
		private string @__ProductsTable;
		
		private System.Nullable<System.DateTime> @__LastProductTime;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnStateChanging(int value);
    partial void OnStateChanged();
    partial void OnSiteChanging(string value);
    partial void OnSiteChanged();
    partial void OnCommandChanging(int value);
    partial void OnCommandChanged();
    partial void OnRunTimeSpanChanging(int value);
    partial void OnRunTimeSpanChanged();
    partial void OnCrawlProductTimeoutChanging(int value);
    partial void OnCrawlProductTimeoutChanged();
    partial void OnYieldProductTimeoutChanging(int value);
    partial void OnYieldProductTimeoutChanged();
    partial void OnAdminEmailsChanging(string value);
    partial void OnAdminEmailsChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnRestartDelayIfBrokenChanging(int value);
    partial void OnRestartDelayIfBrokenChanged();
    partial void On_SessionStartTimeChanging(System.Nullable<System.DateTime> value);
    partial void On_SessionStartTimeChanged();
    partial void On_LastSessionStateChanging(System.Nullable<int> value);
    partial void On_LastSessionStateChanged();
    partial void On_NextStartTimeChanging(System.DateTime value);
    partial void On_NextStartTimeChanged();
    partial void On_LastStartTimeChanging(System.Nullable<System.DateTime> value);
    partial void On_LastStartTimeChanged();
    partial void On_LastEndTimeChanging(System.Nullable<System.DateTime> value);
    partial void On_LastEndTimeChanged();
    partial void On_LastProcessIdChanging(System.Nullable<int> value);
    partial void On_LastProcessIdChanged();
    partial void On_LastLogChanging(string value);
    partial void On_LastLogChanged();
    partial void On_ArchiveChanging(string value);
    partial void On_ArchiveChanged();
    partial void On_ProductsTableChanging(string value);
    partial void On_ProductsTableChanged();
    partial void On_LastProductTimeChanging(System.Nullable<System.DateTime> value);
    partial void On_LastProductTimeChanged();
    #endregion
		
		public Crawler()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Int NOT NULL")]
		public int State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Site", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Site
		{
			get
			{
				return this._Site;
			}
			set
			{
				if ((this._Site != value))
				{
					this.OnSiteChanging(value);
					this.SendPropertyChanging();
					this._Site = value;
					this.SendPropertyChanged("Site");
					this.OnSiteChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Command", DbType="Int NOT NULL")]
		public int Command
		{
			get
			{
				return this._Command;
			}
			set
			{
				if ((this._Command != value))
				{
					this.OnCommandChanging(value);
					this.SendPropertyChanging();
					this._Command = value;
					this.SendPropertyChanged("Command");
					this.OnCommandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RunTimeSpan", DbType="Int NOT NULL")]
		public int RunTimeSpan
		{
			get
			{
				return this._RunTimeSpan;
			}
			set
			{
				if ((this._RunTimeSpan != value))
				{
					this.OnRunTimeSpanChanging(value);
					this.SendPropertyChanging();
					this._RunTimeSpan = value;
					this.SendPropertyChanged("RunTimeSpan");
					this.OnRunTimeSpanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CrawlProductTimeout", DbType="Int NOT NULL")]
		public int CrawlProductTimeout
		{
			get
			{
				return this._CrawlProductTimeout;
			}
			set
			{
				if ((this._CrawlProductTimeout != value))
				{
					this.OnCrawlProductTimeoutChanging(value);
					this.SendPropertyChanging();
					this._CrawlProductTimeout = value;
					this.SendPropertyChanged("CrawlProductTimeout");
					this.OnCrawlProductTimeoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YieldProductTimeout", DbType="Int NOT NULL")]
		public int YieldProductTimeout
		{
			get
			{
				return this._YieldProductTimeout;
			}
			set
			{
				if ((this._YieldProductTimeout != value))
				{
					this.OnYieldProductTimeoutChanging(value);
					this.SendPropertyChanging();
					this._YieldProductTimeout = value;
					this.SendPropertyChanged("YieldProductTimeout");
					this.OnYieldProductTimeoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminEmails", DbType="NVarChar(300) NOT NULL", CanBeNull=false)]
		public string AdminEmails
		{
			get
			{
				return this._AdminEmails;
			}
			set
			{
				if ((this._AdminEmails != value))
				{
					this.OnAdminEmailsChanging(value);
					this.SendPropertyChanging();
					this._AdminEmails = value;
					this.SendPropertyChanged("AdminEmails");
					this.OnAdminEmailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(1000)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RestartDelayIfBroken", DbType="Int NOT NULL")]
		public int RestartDelayIfBroken
		{
			get
			{
				return this._RestartDelayIfBroken;
			}
			set
			{
				if ((this._RestartDelayIfBroken != value))
				{
					this.OnRestartDelayIfBrokenChanging(value);
					this.SendPropertyChanging();
					this._RestartDelayIfBroken = value;
					this.SendPropertyChanged("RestartDelayIfBroken");
					this.OnRestartDelayIfBrokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_SessionStartTime]", Storage="__SessionStartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> _SessionStartTime
		{
			get
			{
				return this.@__SessionStartTime;
			}
			set
			{
				if ((this.@__SessionStartTime != value))
				{
					this.On_SessionStartTimeChanging(value);
					this.SendPropertyChanging();
					this.@__SessionStartTime = value;
					this.SendPropertyChanged("_SessionStartTime");
					this.On_SessionStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_LastSessionState]", Storage="__LastSessionState", DbType="Int")]
		public System.Nullable<int> _LastSessionState
		{
			get
			{
				return this.@__LastSessionState;
			}
			set
			{
				if ((this.@__LastSessionState != value))
				{
					this.On_LastSessionStateChanging(value);
					this.SendPropertyChanging();
					this.@__LastSessionState = value;
					this.SendPropertyChanged("_LastSessionState");
					this.On_LastSessionStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_NextStartTime]", Storage="__NextStartTime", DbType="DateTime NOT NULL")]
		public System.DateTime _NextStartTime
		{
			get
			{
				return this.@__NextStartTime;
			}
			set
			{
				if ((this.@__NextStartTime != value))
				{
					this.On_NextStartTimeChanging(value);
					this.SendPropertyChanging();
					this.@__NextStartTime = value;
					this.SendPropertyChanged("_NextStartTime");
					this.On_NextStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_LastStartTime]", Storage="__LastStartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> _LastStartTime
		{
			get
			{
				return this.@__LastStartTime;
			}
			set
			{
				if ((this.@__LastStartTime != value))
				{
					this.On_LastStartTimeChanging(value);
					this.SendPropertyChanging();
					this.@__LastStartTime = value;
					this.SendPropertyChanged("_LastStartTime");
					this.On_LastStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_LastEndTime]", Storage="__LastEndTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> _LastEndTime
		{
			get
			{
				return this.@__LastEndTime;
			}
			set
			{
				if ((this.@__LastEndTime != value))
				{
					this.On_LastEndTimeChanging(value);
					this.SendPropertyChanging();
					this.@__LastEndTime = value;
					this.SendPropertyChanged("_LastEndTime");
					this.On_LastEndTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_LastProcessId]", Storage="__LastProcessId", DbType="Int")]
		public System.Nullable<int> _LastProcessId
		{
			get
			{
				return this.@__LastProcessId;
			}
			set
			{
				if ((this.@__LastProcessId != value))
				{
					this.On_LastProcessIdChanging(value);
					this.SendPropertyChanging();
					this.@__LastProcessId = value;
					this.SendPropertyChanged("_LastProcessId");
					this.On_LastProcessIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_LastLog]", Storage="__LastLog", DbType="NVarChar(500)")]
		public string _LastLog
		{
			get
			{
				return this.@__LastLog;
			}
			set
			{
				if ((this.@__LastLog != value))
				{
					this.On_LastLogChanging(value);
					this.SendPropertyChanging();
					this.@__LastLog = value;
					this.SendPropertyChanged("_LastLog");
					this.On_LastLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_Archive]", Storage="__Archive", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string _Archive
		{
			get
			{
				return this.@__Archive;
			}
			set
			{
				if ((this.@__Archive != value))
				{
					this.On_ArchiveChanging(value);
					this.SendPropertyChanging();
					this.@__Archive = value;
					this.SendPropertyChanged("_Archive");
					this.On_ArchiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_ProductsTable]", Storage="__ProductsTable", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string _ProductsTable
		{
			get
			{
				return this.@__ProductsTable;
			}
			set
			{
				if ((this.@__ProductsTable != value))
				{
					this.On_ProductsTableChanging(value);
					this.SendPropertyChanging();
					this.@__ProductsTable = value;
					this.SendPropertyChanged("_ProductsTable");
					this.On_ProductsTableChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_LastProductTime]", Storage="__LastProductTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> _LastProductTime
		{
			get
			{
				return this.@__LastProductTime;
			}
			set
			{
				if ((this.@__LastProductTime != value))
				{
					this.On_LastProductTimeChanging(value);
					this.SendPropertyChanging();
					this.@__LastProductTime = value;
					this.SendPropertyChanged("_LastProductTime");
					this.On_LastProductTimeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Messages")]
	public partial class Message : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _Source;
		
		private int _Type;
		
		private string _Value;
		
		private System.DateTime _Time;
		
		private string _Details;
		
		private System.Nullable<int> _Mark;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnTypeChanging(int value);
    partial void OnTypeChanged();
    partial void OnValueChanging(string value);
    partial void OnValueChanged();
    partial void OnTimeChanging(System.DateTime value);
    partial void OnTimeChanged();
    partial void OnDetailsChanging(string value);
    partial void OnDetailsChanged();
    partial void OnMarkChanging(System.Nullable<int> value);
    partial void OnMarkChanged();
    #endregion
		
		public Message()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Time", DbType="DateTime NOT NULL")]
		public System.DateTime Time
		{
			get
			{
				return this._Time;
			}
			set
			{
				if ((this._Time != value))
				{
					this.OnTimeChanging(value);
					this.SendPropertyChanging();
					this._Time = value;
					this.SendPropertyChanged("Time");
					this.OnTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Details", DbType="NVarChar(MAX)")]
		public string Details
		{
			get
			{
				return this._Details;
			}
			set
			{
				if ((this._Details != value))
				{
					this.OnDetailsChanging(value);
					this.SendPropertyChanging();
					this._Details = value;
					this.SendPropertyChanged("Details");
					this.OnDetailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mark", DbType="Int")]
		public System.Nullable<int> Mark
		{
			get
			{
				return this._Mark;
			}
			set
			{
				if ((this._Mark != value))
				{
					this.OnMarkChanging(value);
					this.SendPropertyChanging();
					this._Mark = value;
					this.SendPropertyChanged("Mark");
					this.OnMarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Services")]
	public partial class Service : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Id;
		
		private int _State;
		
		private string _ExeFolder;
		
		private int _Command;
		
		private int _RunTimeSpan;
		
		private int _RunTimeout;
		
		private string _AdminEmails;
		
		private string _Comment;
		
		private int _RestartDelayIfBroken;
		
		private System.Nullable<int> @__LastSessionState;
		
		private System.DateTime @__NextStartTime;
		
		private System.Nullable<System.DateTime> @__LastStartTime;
		
		private System.Nullable<System.DateTime> @__LastEndTime;
		
		private System.Nullable<int> @__LastProcessId;
		
		private string @__LastLog;
		
		private string @__Archive;
		
		private string @__Data;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(string value);
    partial void OnIdChanged();
    partial void OnStateChanging(int value);
    partial void OnStateChanged();
    partial void OnExeFolderChanging(string value);
    partial void OnExeFolderChanged();
    partial void OnCommandChanging(int value);
    partial void OnCommandChanged();
    partial void OnRunTimeSpanChanging(int value);
    partial void OnRunTimeSpanChanged();
    partial void OnRunTimeoutChanging(int value);
    partial void OnRunTimeoutChanged();
    partial void OnAdminEmailsChanging(string value);
    partial void OnAdminEmailsChanged();
    partial void OnCommentChanging(string value);
    partial void OnCommentChanged();
    partial void OnRestartDelayIfBrokenChanging(int value);
    partial void OnRestartDelayIfBrokenChanged();
    partial void On_LastSessionStateChanging(System.Nullable<int> value);
    partial void On_LastSessionStateChanged();
    partial void On_NextStartTimeChanging(System.DateTime value);
    partial void On_NextStartTimeChanged();
    partial void On_LastStartTimeChanging(System.Nullable<System.DateTime> value);
    partial void On_LastStartTimeChanged();
    partial void On_LastEndTimeChanging(System.Nullable<System.DateTime> value);
    partial void On_LastEndTimeChanged();
    partial void On_LastProcessIdChanging(System.Nullable<int> value);
    partial void On_LastProcessIdChanged();
    partial void On_LastLogChanging(string value);
    partial void On_LastLogChanged();
    partial void On_ArchiveChanging(string value);
    partial void On_ArchiveChanged();
    partial void On_DataChanging(string value);
    partial void On_DataChanged();
    #endregion
		
		public Service()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_State", DbType="Int NOT NULL")]
		public int State
		{
			get
			{
				return this._State;
			}
			set
			{
				if ((this._State != value))
				{
					this.OnStateChanging(value);
					this.SendPropertyChanging();
					this._State = value;
					this.SendPropertyChanged("State");
					this.OnStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ExeFolder", DbType="NVarChar(MAX)")]
		public string ExeFolder
		{
			get
			{
				return this._ExeFolder;
			}
			set
			{
				if ((this._ExeFolder != value))
				{
					this.OnExeFolderChanging(value);
					this.SendPropertyChanging();
					this._ExeFolder = value;
					this.SendPropertyChanged("ExeFolder");
					this.OnExeFolderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Command", DbType="Int NOT NULL")]
		public int Command
		{
			get
			{
				return this._Command;
			}
			set
			{
				if ((this._Command != value))
				{
					this.OnCommandChanging(value);
					this.SendPropertyChanging();
					this._Command = value;
					this.SendPropertyChanged("Command");
					this.OnCommandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RunTimeSpan", DbType="Int NOT NULL")]
		public int RunTimeSpan
		{
			get
			{
				return this._RunTimeSpan;
			}
			set
			{
				if ((this._RunTimeSpan != value))
				{
					this.OnRunTimeSpanChanging(value);
					this.SendPropertyChanging();
					this._RunTimeSpan = value;
					this.SendPropertyChanged("RunTimeSpan");
					this.OnRunTimeSpanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RunTimeout", DbType="Int NOT NULL")]
		public int RunTimeout
		{
			get
			{
				return this._RunTimeout;
			}
			set
			{
				if ((this._RunTimeout != value))
				{
					this.OnRunTimeoutChanging(value);
					this.SendPropertyChanging();
					this._RunTimeout = value;
					this.SendPropertyChanged("RunTimeout");
					this.OnRunTimeoutChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AdminEmails", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string AdminEmails
		{
			get
			{
				return this._AdminEmails;
			}
			set
			{
				if ((this._AdminEmails != value))
				{
					this.OnAdminEmailsChanging(value);
					this.SendPropertyChanging();
					this._AdminEmails = value;
					this.SendPropertyChanged("AdminEmails");
					this.OnAdminEmailsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Comment", DbType="NVarChar(MAX)")]
		public string Comment
		{
			get
			{
				return this._Comment;
			}
			set
			{
				if ((this._Comment != value))
				{
					this.OnCommentChanging(value);
					this.SendPropertyChanging();
					this._Comment = value;
					this.SendPropertyChanged("Comment");
					this.OnCommentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RestartDelayIfBroken", DbType="Int NOT NULL")]
		public int RestartDelayIfBroken
		{
			get
			{
				return this._RestartDelayIfBroken;
			}
			set
			{
				if ((this._RestartDelayIfBroken != value))
				{
					this.OnRestartDelayIfBrokenChanging(value);
					this.SendPropertyChanging();
					this._RestartDelayIfBroken = value;
					this.SendPropertyChanged("RestartDelayIfBroken");
					this.OnRestartDelayIfBrokenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_LastSessionState]", Storage="__LastSessionState", DbType="Int")]
		public System.Nullable<int> _LastSessionState
		{
			get
			{
				return this.@__LastSessionState;
			}
			set
			{
				if ((this.@__LastSessionState != value))
				{
					this.On_LastSessionStateChanging(value);
					this.SendPropertyChanging();
					this.@__LastSessionState = value;
					this.SendPropertyChanged("_LastSessionState");
					this.On_LastSessionStateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_NextStartTime]", Storage="__NextStartTime", DbType="DateTime NOT NULL")]
		public System.DateTime _NextStartTime
		{
			get
			{
				return this.@__NextStartTime;
			}
			set
			{
				if ((this.@__NextStartTime != value))
				{
					this.On_NextStartTimeChanging(value);
					this.SendPropertyChanging();
					this.@__NextStartTime = value;
					this.SendPropertyChanged("_NextStartTime");
					this.On_NextStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_LastStartTime]", Storage="__LastStartTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> _LastStartTime
		{
			get
			{
				return this.@__LastStartTime;
			}
			set
			{
				if ((this.@__LastStartTime != value))
				{
					this.On_LastStartTimeChanging(value);
					this.SendPropertyChanging();
					this.@__LastStartTime = value;
					this.SendPropertyChanged("_LastStartTime");
					this.On_LastStartTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_LastEndTime]", Storage="__LastEndTime", DbType="DateTime")]
		public System.Nullable<System.DateTime> _LastEndTime
		{
			get
			{
				return this.@__LastEndTime;
			}
			set
			{
				if ((this.@__LastEndTime != value))
				{
					this.On_LastEndTimeChanging(value);
					this.SendPropertyChanging();
					this.@__LastEndTime = value;
					this.SendPropertyChanged("_LastEndTime");
					this.On_LastEndTimeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_LastProcessId]", Storage="__LastProcessId", DbType="Int")]
		public System.Nullable<int> _LastProcessId
		{
			get
			{
				return this.@__LastProcessId;
			}
			set
			{
				if ((this.@__LastProcessId != value))
				{
					this.On_LastProcessIdChanging(value);
					this.SendPropertyChanging();
					this.@__LastProcessId = value;
					this.SendPropertyChanged("_LastProcessId");
					this.On_LastProcessIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_LastLog]", Storage="__LastLog", DbType="NVarChar(MAX)")]
		public string _LastLog
		{
			get
			{
				return this.@__LastLog;
			}
			set
			{
				if ((this.@__LastLog != value))
				{
					this.On_LastLogChanging(value);
					this.SendPropertyChanging();
					this.@__LastLog = value;
					this.SendPropertyChanged("_LastLog");
					this.On_LastLogChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_Archive]", Storage="__Archive", DbType="NText", UpdateCheck=UpdateCheck.Never)]
		public string _Archive
		{
			get
			{
				return this.@__Archive;
			}
			set
			{
				if ((this.@__Archive != value))
				{
					this.On_ArchiveChanging(value);
					this.SendPropertyChanging();
					this.@__Archive = value;
					this.SendPropertyChanged("_Archive");
					this.On_ArchiveChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[_Data]", Storage="__Data", DbType="NVarChar(MAX)")]
		public string _Data
		{
			get
			{
				return this.@__Data;
			}
			set
			{
				if ((this.@__Data != value))
				{
					this.On_DataChanging(value);
					this.SendPropertyChanging();
					this.@__Data = value;
					this.SendPropertyChanged("_Data");
					this.On_DataChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Settings")]
	public partial class Setting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Scope;
		
		private string _Key;
		
		private string _Value;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnScopeChanging(string value);
    partial void OnScopeChanged();
    partial void OnKeyChanging(string value);
    partial void OnKeyChanged();
    partial void OnValueChanging(string value);
    partial void OnValueChanged();
    #endregion
		
		public Setting()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Scope", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Scope
		{
			get
			{
				return this._Scope;
			}
			set
			{
				if ((this._Scope != value))
				{
					this.OnScopeChanging(value);
					this.SendPropertyChanging();
					this._Scope = value;
					this.SendPropertyChanged("Scope");
					this.OnScopeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[Key]", Storage="_Key", DbType="NVarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Key
		{
			get
			{
				return this._Key;
			}
			set
			{
				if ((this._Key != value))
				{
					this.OnKeyChanging(value);
					this.SendPropertyChanging();
					this._Key = value;
					this.SendPropertyChanged("Key");
					this.OnKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="NText NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
