//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliver.BotWeb.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    public sealed partial class Spider : global::System.Configuration.ApplicationSettingsBase {
        
        private static Spider defaultInstance = ((Spider)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Spider())));
        
        public static Spider Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ComplyRobotProtocol {
            get {
                return ((bool)(this["ComplyRobotProtocol"]));
            }
            set {
                this["ComplyRobotProtocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int MaxDownloadLinkDepth {
            get {
                return ((int)(this["MaxDownloadLinkDepth"]));
            }
            set {
                this["MaxDownloadLinkDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1000")]
        public int MaxPageCountPerSite {
            get {
                return ((int)(this["MaxPageCountPerSite"]));
            }
            set {
                this["MaxPageCountPerSite"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int UnchangableDomainPartNumber {
            get {
                return ((int)(this["UnchangableDomainPartNumber"]));
            }
            set {
                this["UnchangableDomainPartNumber"] = value;
            }
        }
    }
}
