//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliver.CrawlerHost.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Host : global::System.Configuration.ApplicationSettingsBase {
        
        private static Host defaultInstance = ((Host)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Host())));
        
        public static Host Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CrawlerHostPath {
            get {
                return ((string)(this["CrawlerHostPath"]));
            }
            set {
                this["CrawlerHostPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SOFTWARE\\CliverSoft\\CliverBot")]
        public string RegistrySubkey {
            get {
                return ((string)(this["RegistrySubkey"]));
            }
            set {
                this["RegistrySubkey"] = value;
            }
        }
    }
}
