//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliver.CrawlerHostManager.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5000")]
        public int PollIntervalInMss {
            get {
                return ((int)(this["PollIntervalInMss"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\Crawlers")]
        public string CrawlersDirectory {
            get {
                return ((string)(this["CrawlersDirectory"]));
            }
            set {
                this["CrawlersDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public int CrawlerProcessMaxNumber {
            get {
                return ((int)(this["CrawlerProcessMaxNumber"]));
            }
            set {
                this["CrawlerProcessMaxNumber"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://cliversoft.com/articles/manual_to_crawlerhost.php")]
        public string HelpUri {
            get {
                return ((string)(this["HelpUri"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool NoDialogMode {
            get {
                return ((bool)(this["NoDialogMode"]));
            }
            set {
                this["NoDialogMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("..\\..\\")]
        public string ServiceDirectory {
            get {
                return ((string)(this["ServiceDirectory"]));
            }
            set {
                this["ServiceDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int ServiceProcessMaxNumber {
            get {
                return ((int)(this["ServiceProcessMaxNumber"]));
            }
            set {
                this["ServiceProcessMaxNumber"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2000000")]
        public int LogFileChunkSizeInBytes {
            get {
                return ((int)(this["LogFileChunkSizeInBytes"]));
            }
            set {
                this["LogFileChunkSizeInBytes"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(LocalDB)\\MSSQLLocalDB;AttachDbFilename=\"D:\\_d\\_PROJECTS\\FHR(for Andr" +
            "eas Chermak)\\CliverHost\\CliverCrawlerHost\\CliverCrawlerHost.mdf\";Integrated Secu" +
            "rity=True;Connect Timeout=30")]
        public string CliverCrawlerHostConnectionString {
            get {
                return ((string)(this["CliverCrawlerHostConnectionString"]));
            }
        }
    }
}
